<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Post;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByTitleQuery($title)
    {
        return $this->createQueryBuilder('p')
            ->where('p.title LIKE :title')
            ->setParameter(':title', "%$title%")
            ->getQuery()
        ;
    }

    /**
     * @return Post[]
     */
    public function findPopularPost()
    {
        return $this->createQueryBuilder('p')
            ->orderBy('p.rating', 'DESC')
            ->setMaxResults(5)
            ->getQuery()
            ->getResult()
        ;
    }
}
