index:
    path:      /
    defaults:  { _controller: AppBundle:Default:index }

post_create:
    path:      post/create
    defaults:  { _controller: AppBundle:Post:create }

post_edit:
    path:      post/edit/{id}
    defaults:  { _controller: AppBundle:Post:edit }

post_delete:
    path:      post/delete/{id}
    defaults:  { _controller: AppBundle:Post:delete }

post:
    path:      post/{id}
    defaults:  { _controller: AppBundle:Post:index }

admin:
    path:      admin
    defaults:  { _controller: AppBundle:Admin:index }

