index:
    path:      /
    defaults:  { _controller: AppBundle:Default:index }

comment_create:
    path:      comment/create
    defaults:  { _controller: AppBundle:Comment:create }

comment:
    path:      comment
    defaults:  { _controller: AppBundle:Comment:index }

post_create:
    path:      post/create
    defaults:  { _controller: AppBundle:Post:create }

posts_refactor:
    path:      post/refactor
    defaults:  { _controller: AppBundle:Admin:refactor }

post_edit:
    path:      post/edit/{id}
    defaults:  { _controller: AppBundle:Post:edit }
    requirements:
        id: \d+

post_delete:
    path:      post/delete/{id}
    defaults:  { _controller: AppBundle:Post:delete }
    requirements:
        id: \d+

post_search:
    path:      search/post
    defaults:  { _controller: AppBundle:Post:search }

post:
    path:      post/{id}
    defaults:  { _controller: AppBundle:Post:index }
    requirements:
        id: \d+

admin:
    path:      admin
    defaults:  { _controller: AppBundle:Admin:index }

author:
    path:      author/{id}
    defaults:  { _controller: AppBundle:Author:post }


authors:
    path:      authors
    defaults:  { _controller: AppBundle:Author:index }

show_post:
    path:      posts/show
    defaults:  { _controller: AppBundle:Post:loadMore }
