index:
    path:      /
    defaults:  { _controller: AppBundle:Default:index }

admin:
    path:      admin
    defaults:  { _controller: AppBundle:Admin:index }

post_create:
    path:      post/create
    defaults:  { _controller: AppBundle:Post:create }

post:
    path:      post/{id}
    defaults:  { _controller: AppBundle:Post:index }

